version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RACK_ENV=development
    command: bundle exec shotgun -o 0.0.0.0 -p 3000 app.rb 